### ISSUE TITLE
[질문] deploy.sh 수정 관련 질문드립니다.

### ISSUE THREAD

**Issue by Gjunghoon** [sangw0804/chunmyung#115]
### 1. deploy.sh 수정 관련
https://github.com/sangw0804/chunmyung/commit/0443777ba1a606c3b6764e0a810e6dc21761e931

에서 확인할 수 있듯이,
``` 
- docker build --tag sangw0804/chunmyung-client:latest --tag sangw0804/chunmyung-client:$SHA -f ./client/Dockerfile ./client
+ docker build --tag sangw0804/alarmtalk-job:latest --tag sangw0804/alarmtalk-job:$SHA -f ./worker/Dockerfile ./worker
```
**질문)** 클라이언트 이미지를 빌드하는 것을 없애고 alarmtalk job을 빌드하는 것이 추가가 되었던데 클라이언트 이미지를 빌드하는 코드를 삭제하신 이유가 있나요? 배포를 하다가 client pod만 image를 pull하는데 오류가 나서, 
https://github.com/sangw0804/chunmyung/commit/354252ec04a2affbb60e4e6efcb3ab41bb65bbfa

커밋에서 확인하실 수 있듯이
```
+ docker build --tag sangw0804/chunmyung-client:latest --tag sangw0804/chunmyung-client:$SHA -f ./client/Dockerfile ./client
```
클라이언트 이미지를 빌드하는 코드를 추가했습니다. 이렇게 제가 추가한 것이
**질문)**
1. 알람톡 배포상 추가하면 안 되는 코드 인가요?
2. 위 코드를 추가한 위치(맨 위)가 적절한 위치인가요? 배포가 되었을 때 아무런 이상은 없었습니다.

**Comment by sangw0804** [comment]
내가 저거 만들때 실수로 지우고 커밋했나보네 잘 고쳤으 ㅇㅇ.
위치는 저기로 해도 아무 문제 없을겨
